Feature/button component
isdi-coders-2023/coding-adventure-Raul-Mullor-front-202301-BCN pull request #1
Opened 2023-02-27 16:09 UTC by RaulMullor

2023-02-27 16:18 UTC, MMLORENA requested changes
Te faltan los resets y estilos generales.

2023-02-27 16:18 UTC, MMLORENA commented on src/components/TheButton/TheButtonStyled.tsx
> +  border: none;
Te faltan estilos del button

2023-02-27 16:18 UTC, MMLORENA commented on tsconfig.json
> -  "include": ["src"]
¿Por qué has añadido este archivo al tsconfig?

2023-02-27 16:27 UTC, RaulMullor commented on src/components/TheButton/TheButtonStyled.tsx
> +  border: none;
Si ya los tengo hecho para el siguiente push los estilos generales.

2023-02-27 16:28 UTC, RaulMullor commented on tsconfig.json
> -  "include": ["src"]
lo necesitaba

2023-02-27 16:29 UTC, MMLORENA commented on src/components/TheButton/TheButtonStyled.tsx
> +  border: none;
Ok, pero subelo al siguiente

2023-02-27 16:29 UTC, MMLORENA commented
@RaulMullor Ya tienes un test, quita del script el passWithNoTest

2023-02-27 16:29 UTC, MMLORENA commented on tsconfig.json
> -  "include": ["src"]
¿para qué?

2023-02-27 16:42 UTC, MMLORENA requested changes

2023-02-27 16:42 UTC, MMLORENA commented on GloblaStyles.tsx
> +  padding: 0;
Te faltan más resets que estos

2023-02-27 16:42 UTC, MMLORENA commented on package.json
>    },
Quita el script de pastWithNoTest

2023-02-27 16:42 UTC, MMLORENA commented on package.json
>    },
Y deberías usar variables de CSS o el ThemeProvider para no repetir, colores, fuentes y tamaños en toda la App

2023-02-27 16:43 UTC, RaulMullor commented on src/components/TheButton/TheButtonStyled.tsx
> +  border: none;
pero si ya los subi Lore

2023-02-27 17:27 UTC, MMLORENA submitted a review, later dismissed

2023-02-27 17:27 UTC, MMLORENA commented on tsconfig.json
> -  "include": ["src"]
No mientas, está feo menir

2023-02-27 17:27 UTC, MMLORENA commented on src/index.tsx
> +    <TheButton text={"Sign up"} />
El enunciado no hablaba de renderizarlo en App

2023-02-28 10:41 UTC, RaulMullor commented on src/index.tsx
> +    <TheButton text={"Sign up"} />
es imposible teneros contentos Lorena

2023-02-28 10:41 UTC, RaulMullor commented on tsconfig.json
> -  "include": ["src"]
necesito que seas mas especifica, puse 3 excusas distintas en la misma frase

2023-02-28 12:15 UTC, benjaminrae commented
@RaulMullor Falla el workflow de testing 👀

2023-02-28 12:17 UTC, MMLORENA commented on src/index.tsx
> +    <TheButton text={"Sign up"} />
No te lo voy a poner fácil

2023-02-28 14:24 UTC, RaulMullor commented on GloblaStyles.tsx
> +  padding: 0;
Los tengo puestos lorena

2023-02-28 15:59 UTC, catatarelli requested changes

2023-03-02 10:43 UTC, RaulMullor commented on src/GloblaStyles.tsx
> +  }
ya esta puesto

2023-03-02 10:44 UTC, RaulMullor commented on src/components/TheButton/TheButton.test.tsx
> +  describe("When its rendered", () => {
corregido

2023-03-02 10:54 UTC, catatarelli approved these changes

2023-03-02 10:54 UTC, catatarelli commented on src/components/TheButton/TheButton.test.tsx
> +  describe("When its rendered with the text Sing Up", () => {
se renderiza con el text Sign up o con el text eee you?

2023-03-02 10:54 UTC, merged