Feature/form component
isdi-coders-2023/coding-adventure-Raul-Mullor-front-202301-BCN pull request #2
Opened 2023-02-28 15:23 UTC by RaulMullor

2023-02-28 15:28 UTC, catatarelli requested changes

2023-02-28 15:43 UTC, RaulMullor commented on GlobalStyles.tsx
> +  margin: 0;
cambie cositas a ver si esta mejor

2023-03-02 10:55 UTC, catatarelli approved these changes

2023-03-02 10:55 UTC, catatarelli commented on src/components/FormComponent/FormComponent.tsx
> +      <button></button>
tiene un button arriba el form?

2023-03-02 10:55 UTC, catatarelli commented
Dale estilos al formulario (no dar estilo al input type file).

2023-03-02 10:57 UTC, RaulMullor commented on src/components/FormComponent/FormComponent.tsx
> +      <button></button>
ya lo quite

2023-03-02 12:07 UTC, merged